### ISSUE TITLE
Wrong copy/paste command chosen on some systems

### ISSUE THREAD

**Issue by Aethor** [snmsts/trivial-clipboard#16]
Hi,

I found a case where the command finding mechanism is not general enough. I use Fedora, where you can have both Wayland and X, and you choose which one to use when logging in. This lead to a case where I can use X, but `wl-copy` still exists. Therefore, when evaluating `(trivial-clipboard:text "some text")` using X, I get an error because:

- `trivial-clipboard:find-copy-command` finds `wl-copy` first
- `wl-copy` fails afterwards (which makes sense since Wayland is not started)

So relying on whether or not the command exists does not seem to handle all case. Maybe selecting a command should be done based on if it returns an error code or not ? In this case, `wl-copy` should be tried and, because it returns an error code, `xclip` should be selected instead. Let me know your thoughts on the issue. Happy to submit a PR if you're interested.

**Comment by aadcg** [comment]
@Aethor I just noticed this issue as well.

> relying on whether or not the command exists does not seem to handle all case. Maybe selecting a command should be done based on if it returns an error code or not ?

That's one option. An easier solution that might be to set the right command according to `(uiop:getenvp "XDG_SESSION_TYPE")`.

CC @snmsts

**Comment by snmsts** [comment]
PR is welcomed.

**Comment by Aethor** [comment]
Opened PR #17 to fix the issue, don't hesitate to send feedback

**Comment by Aethor** [comment]
I'm closing this issue since #17 got merged - thanks!
