### ISSUE TITLE
Find the right clipboard commands

### ISSUE THREAD

**Issue by aadcg** [snmsts/trivial-clipboard#18]
#17 was a major improvement on the goal of setting the right clipboard command. [I found out that it may be the case that a user is using X11 but `XDG_SESSION_TYPE` is set to `tty` instead of `x11`](https://discourse.atlas.engineer/t/unable-to-copy-paste/850/5). I suggest to fallback on `xclip` or `xsel` if they're found regardless of the value of `XDG_SESSION_TYPE`. In other words, check `XDG_SESSION_TYPE` for Wayland exclusively.

@aartaka you run StumpWM, correct? What's the output of `env | grep XDG_SESSION_TYPE`?

**Comment by aartaka** [comment]
> aartaka you run StumpWM, correct? What's the output of `env | grep XDG_SESSION_TYPE`?

It says x11
