### ISSUE TITLE
Support wayland

### ISSUE THREAD

**Issue by Ambrevar** [snmsts/trivial-clipboard#8]
We could use wl-copy to support Wayland.
See https://github.com/atlas-engineer/nyxt/issues/924.

**Comment by craftyguy** [comment]
https://github.com/bugaevc/wl-clipboard

That provides two utilities that manage the clipboard in Wayland, wl-copy and wl-paste. There might be other options too, but that project is the only one I've heard of/used.

**Comment by snmsts** [comment]
patch are welcomed. For this issue I don't use wayland environment... so I can't test it quickly.

**Comment by Ambrevar** [comment]
@craftyguy Do you know enough Common Lisp to send a patch?

**Comment by snmsts** [comment]
@Ambrevar Thank you for your followups and I'm quite amazed that nyxt have already users which developers might need care the possibility of users which have no common lisp background... my set of software always require common lisp background...

anyway... I made and apply patch which I didn't check. (hope it isn't confusing for non lisp folks)
@craftyguy would you try it?

Thank you anyway.

**Comment by Ambrevar** [comment]
Thanks @snmsts, looks like https://github.com/snmsts/trivial-clipboard/commit/afcd3743b842f5a81fc86dba60f9db59970f49c5 would work.  @craftyguy can you confirm before I update the Guix package?

**Comment by craftyguy** [comment]
@Ambrevar I'm not currently using nyxt, and I'm not sure how else I might be able to test this.

**Comment by snmsts** [comment]
mmm... which linux dist would be good to try wl-clipboard?

**Comment by craftyguy** [comment]
I think any with a wayland DE/WM would be good. I'm on Arch Linux with Sway.

**Comment by snmsts** [comment]
Thank you!

**Comment by Ambrevar** [comment]
I've updated the Guix package, so this change should reflect everywhere
it's used in Guix (e.g. the Nyxt Guix package).

Thank you all!
